### ISSUE TITLE
Deploy to Azure button

### ISSUE THREAD

**Issue by azooinmyluggage** [kzu/wsrelay#3]
One of our MVP reported this issue last week. can you please take a look?
Deploy to Azure button feature gets stuck in the setting up repository step.

![image](https://user-images.githubusercontent.com/6857119/49711085-439fbe80-fbf2-11e8-80d6-cda5aec3c514.png)

regards,
Atul

**Comment by kzu** [comment]
Hi there, 
the MVP reported it precisely because he wanted to use it and it's not working as expected. If you can please try it out and suggest an edit to the [azuredeploy.json](https://github.com/kzu/wsrelay/blob/master/azuredeploy.json) I'd be happy to merge it.
